Resolve tracking config templates
watercooler-labs/toggl-cli pull request #53
Opened 2023-04-12 15:43 UTC by shantanuraj

## :star2: What does this PR do?

- 🧠 Add custom deserialization for BranchConfig
- 🕴️ Store branch config as array
- 🌌 Add custom parsing for TrackConfig
- 🏋️‍♂️ Add `toggl config active`

## :bug: Recommendations for testing

- See config parsing demo.
  [![asciicast](https://asciinema.org/a/qQXexPPkAKHXULne9JM1t8on4.svg)](https://asciinema.org/a/qQXexPPkAKHXULne9JM1t8on4)
- Another demo showing the config matching via the `toggl config active` command
  [![asciicast](https://asciinema.org/a/UlqtsLDukPWfkVSDc6ks4qloS.svg)](https://asciinema.org/a/UlqtsLDukPWfkVSDc6ks4qloS)
- Try running `toggl config` for various macros and shell commands.
- Sample complex configuration with a bunch of shell expansions

```toml
["*"]
description = "🔨 {{branch}} / {{current_dir}}"
project = "{{parent_base_dir}}"
billable = true

["alt"]
description = "chore(release)"
project = "{{base_dir}}"
tags = ["release", "{{parent_dir}}"]
billable = false

# Match all branches that start with a number and a slash
# e.g. 1234/feature-branch
["^\\d+\\/.*"]
description = "🔨 {{branch}}"
project = "{{parent_dir}}/{{base_dir}}"
# Set task to android if the current directory contains "android"
# otherwise set it to iOS
task = """
  {{$if [[ "$PWD" == *"android"* ]]; then echo "Android"; else echo "iOS"; fi}}
"""
# Set tags to the current year
tags = ["code", "{{$ date +\"%Y\" }}"]
billable = true
```

### New commands introduced

```console
# Get active tracking configuration for current directory and branch
$ toggl config active
```

## :memo: Links to relevant issues/docs

See #45 which defines the marcro expansion mechanism.

## :speech_balloon: Summarise how you feel about this PR with a gif/image

![negroni-sbagliato](https://user-images.githubusercontent.com/1716853/231507501-29677828-3c6d-4aea-8425-987490aecb0e.gif)

2023-04-18 18:01 UTC, heytherewill requested changes
This is amazing!

One thing I'd add: Add something in the lines of `[Currently active]` when printing the list of branch configs so that the user only needs the `toggl config active` command if they have a massive config file

2023-04-19 00:14 UTC, shantanuraj commented on src/config/model.rs
> +                        return Ok(command);
So I've cleaned all surrounding code and added proper errors for config related errors in the error crate.

https://github.com/watercooler-labs/toggl-cli/commit/e6441dc1ed52dd18ed9839314302226d9104c692
https://github.com/watercooler-labs/toggl-cli/pull/53/commits/0aa99257257311bf3fd7b5ed9cd42f3d701e01ce

And in https://github.com/watercooler-labs/toggl-cli/commit/1f4dd231c89886b0d318cbe03710b5a1a2c1b8a9 I updated the parser to ignore config values whose macros cannot be substituted.

2023-04-19 00:15 UTC, shantanuraj commented on src/config/model.rs
> +            let output = std::process::Command::new("sh")
I'll need to check with you to run some commands on windows to resolve this one.

2023-04-19 00:23 UTC, shantanuraj commented on src/config/model.rs
> +                        return Ok(command);
Examples for

## Invalid macro
<img width="603" alt="image" src="https://user-images.githubusercontent.com/1716853/232934482-dd4d73e6-9c31-4a2c-a949-e79f41045260.png">

## Shell resolution error
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1716853/232934789-2a380639-be60-4469-b72d-66623a3b6810.png">

2023-04-19 21:31 UTC, merged